### ISSUE TITLE
Integration stopped working on HA 2025.7.3

### ISSUE THREAD

**Issue by antonoal** [amosyuen/ha-tplink-deco#414]
### Problem

Have just updated HA version and realised this integration is failing with the below error in the logs:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/__init__.py", line 167, in async_setup_entry
    hass, hass.config_entries.async_forward_entry_setup(config_entry, platform)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

### TP-Link Deco Version

3.7.0

### Router Model

Deco M9 Plus

### Debugging Information

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_deco/__init__.py", line 167, in async_setup_entry
    hass, hass.config_entries.async_forward_entry_setup(config_entry, platform)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by ee02217** [comment]
Same issue here. Is this still supported?

**Comment by amosyuen** [comment]
Are you sure you have v.3.7.0? async_forward_entry_setup was migrated a while ago since like v1.7.0 https://github.com/amosyuen/ha-tplink-deco/commit/cc19bbb566359bca38639e954713c02b1f01ac06
